[package]
name = "metrics_distributor"
version = "0.3.4"
authors = ["Dirk Gadsden <dirk@esherido.com>"]
description = "Ingest logs and forward aggregated data to APIs/services."
license = "BSD-3-Clause"
repository = "https://github.com/dirk/metrics_distributor"

[dependencies]
hyper = "0.8.1"
iron = "0.3.0"
router = "0.1.0"
regex = "0.1.70"
lazy_static = "0.1.15"
nom = "1.2.3"
chrono = "0.2.20"
rustc-serialize = "0.3.19"

[[example]]
name = "http_server"

[[example]]
name = "statsd_server"
